version: '2'
services:      
    Nacimiento:
      image: node:13.3.0
      working_dir: /usr/app
      command: npm start
      volumes:
        - ./Micro_Servicio_Actas_Nacimiento:/usr/app/
      ports:
        - "9000:9000"
      networks:
        main:
          aliases:
            - Nacimiento
    ClienteInterno:
      image: node:13.3.0
      working_dir: /usr/app
      command: npm start
      volumes:
        - ./Micro_Servicio_Cliente_Interno:/usr/app/
      ports:
        - "9004:9004"
      networks:
        main:
          aliases:
            - ClienteInterno
    Defuncion:
      image: node:13.3.0
      working_dir: /usr/app
      command: npm start
      volumes:
        - ./Micro_Servicio_Actas_Defuncion:/usr/app/
      ports:
        - "9002:9002"
      networks:
          main:
            aliases:
              - Defuncion
    Divorcio:
      image: node:13.3.0
      working_dir: /usr/app
      command: npm start
      volumes:
        - ./Micro_Servicio_Actas_Divorcio:/usr/app/
      ports:
        - "9003:9003"
      networks:
        main:
          aliases:
            - Divorcio
    Matrimonio:
      image: node:13.3.0
      working_dir: /usr/app
      command: npm start
      volumes:
        - ./Micro_Servicio_Actas_Matrimonio:/usr/app/
      ports:
        - "9001:9001"
      networks:
        main:
          aliases:
            - Matrimonio    
    Almacenamiento:
      image: node:13.3.0
      working_dir: /usr/app
      command: node index.js
      volumes:
        - ./Micro_Servicio_Almacenamiento:/usr/app/
      ports:
        - "9006:9006"
      networks:
        main:
          aliases:
            - Almacenamiento
    ServiceBusA:
      image: node:13.3.0
      working_dir: /usr/app
      command: node index.js
      volumes:
        - ./Micro_Servicio_ESB:/usr/app/
      ports:
        - "10001:10000"
      networks:
        main:
          aliases:
            - ServiceBusA
    ServiceBusB:
      image: node:13.3.0
      working_dir: /usr/app
      command: node index.js
      volumes:
        - ./Micro_Servicio_ESB:/usr/app/
      ports:
        - "10002:10000"
      networks:
        main:
          aliases:
            - ServiceBusB
    ServiceBus:
        image: nginx
        volumes:
        - ./Nginx_Lb/nginx.conf:/etc/nginx/nginx.conf
        networks:
          main:
            aliases:
              - ServiceBus
networks:
  main:
