version: '2'
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16

services:      
    Nacimiento:
        image: node:13.3.0
        working_dir: /usr/app
        command: npm start
        volumes:
          - ./Micro_Servicio_Actas_Nacimiento:/usr/app/
        ports:
          - "9000:9000"
        networks:
          vpcbr:
            ipv4_address: 10.5.0.2
    ClienteInterno:
        image: node:13.3.0
        working_dir: /usr/app
        command: npm start
        volumes:
          - ./Micro_Servicio_Cliente_Interno:/usr/app/
        ports:
          - "9001:9004"
        networks:
          vpcbr:
            ipv4_address: 10.5.0.4    
    Defuncion:
        image: node:13.3.0
        working_dir: /usr/app
        command: npm start
        volumes:
          - ./Micro_Servicio_Actas_Defuncion:/usr/app/
        ports:
          - "9002:9002"
        networks:
          vpcbr:
            ipv4_address: 10.5.0.5
    Divorcio:
        image: node:13.3.0
        working_dir: /usr/app
        command: npm start
        volumes:
          - ./Micro_Servicio_Actas_Divorcio:/usr/app/
        ports:
          - "9003:9003"
        networks:
          vpcbr:
            ipv4_address: 10.5.0.6
    Matrimonio:
        image: node:13.3.0
        working_dir: /usr/app
        command: npm start
        volumes:
          - ./Micro_Servicio_Actas_Matrimonio:/usr/app/
        ports:
          - "9004:9001"
        networks:
          vpcbr:
            ipv4_address: 10.5.0.7    
    Almacenamiento:
        image: node:13.3.0
        working_dir: /usr/app
        command: node index.js
        volumes:
          - ./Micro_Servicio_Almacenamiento:/usr/app/
        ports:
          - "9006:9006"
        networks:
          vpcbr:
            ipv4_address: 10.5.0.3
    ServiceBus:
        image: node:13.3.0
        working_dir: /usr/app
        command: node index.js
        volumes:
          - ./Micro_Servicio_ESB:/usr/app/
        ports:
          - "10000:10000"
        networks:
          vpcbr:
            ipv4_address: 10.5.0.10